# Generated by Django 4.1.2 on 2024-06-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bici', models.IntegerField(primary_key=True, serialize=False)),
                ('marca_bici', models.CharField(max_length=20)),
                ('modelo_bici', models.CharField(max_length=20)),
                ('tamano_bici', models.CharField(max_length=20)),
                ('precio_bici', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('id_boleta', models.IntegerField()),
                ('monto_boleta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=20)),
                ('apellido_cli', models.CharField(max_length=20)),
                ('correo_cli', models.CharField(max_length=100)),
                ('telefono_cli', models.CharField(max_length=20)),
                ('direccion_cli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=20)),
                ('apellido_emp', models.CharField(max_length=20)),
                ('correo_emp', models.CharField(max_length=100)),
                ('telefono_emp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField()),
                ('monto_factura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_pedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('correo_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('direccion_proveedor', models.CharField(max_length=100)),
                ('tipo_proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBicicleta',
            fields=[
                ('t_bici_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_t_bici', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('t_emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_t_emp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('t_prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_t_prod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('monto_venta', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.empleado')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='bikes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_rep', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ini_rep', models.DateField()),
                ('fecha_fin_rep', models.DateField()),
                ('descripcion_rep', models.CharField(max_length=255)),
                ('estado_rep', models.CharField(max_length=20)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bicicleta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=30)),
                ('precio_prod', models.IntegerField()),
                ('stock_prod', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.proveedor')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.tipoproducto')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='bikes.venta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.tipoempleado'),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.tipobicicleta'),
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('cantidad_arriendo', models.IntegerField()),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bicicleta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.cliente')),
            ],
        ),
    ]
